name: Continuous integration and testing
on:
  push:
    branches: develop
jobs:
  buid_test:
   runs-on: ubuntu-latest
   steps:
    - name: Copy the repo
      uses: actions/checkout@v4
    - name: set up nodejs in the runner
      uses: actions/setup-node@v4
      with:
        node-version: '18.19'
    - name: Install dependencies, build and test
      run: |
        npm ci
        npm test
