name: Build and deploy release
on:
  push:
    branches: main
  repository_dispatch:
    types: trigger-release
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Data reception
      - run: echo "instruction was received to build"
